apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-svc
  namespace: carsties
spec:
  selector:
    matchLabels:
      app: gateway-svc
  template:
    metadata:
      labels:
        app: gateway-svc
    spec:
      containers:
      - name: gateway-svc
        image: jjarnot/carsties-gateway-svc
        imagePullPolicy: Never
        env:
          - name: ClientApp
            value: https://app.carsties.com
          - name: IdentityServiceUrl
            value: https://jj-carsties-dv-identitysvc.azurewebsites.net            
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-clusterip
  namespace: carsties
spec:
  type: ClusterIP
  selector:
    app: gateway-svc
  ports:
  - port: 80
    targetPort: 80